#1
server:
  port: 8771
spring:
 application:
   name: my-eureka-product
#像注册中心注册自己
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

env: env
branch: mycloudbranch
