
server:
  port: 8781

eureka:
  client:
    service-url:
      defalutZone: http://localhost:8761/eureka/

spring:
  application:
    name: order-service

#redis配置信息
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 2000



#自定义负载均衡celve(被调用方的服务器名称，因为fegin内含ribbon，因此在使用feign的时候，使用该配置修改负载策略也有效果)
product-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule


#使用feign超时连接的时间设置(设置请求链接超时时间5s, 设置读数据的超时时间11s)
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 4000
#开启feign对hystrix的支持
  hystrix:
    enabled: true
#设置 禁用hystrix的超时时间(不使用禁用)
#hystrix:
#  command:
#    default:
#      execution:
#        timeout:
#          enabled: false
#修改hystrix超时时间
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 4000

#Hystrix仪表盘监控设置
management:
  endpoints:
    web:
      exposure:
        include: "*"
